# Generated by Django 5.1.3 on 2024-11-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('plot', models.TextField()),
                ('book_format', models.CharField(choices=[('electronic', 'Electronic'), ('physical', 'Physical')], default='physical', max_length=10)),
                ('word_count', models.PositiveIntegerField()),
                ('read_time', models.IntegerField(default=0)),
                ('amoun_of_series', models.CharField(max_length=2)),
            ],
        ),
    ]
