# Generated by Django 5.1.3 on 2024-11-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_amoun_of_series_alter_book_read_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amoun_of_series',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='read_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
